<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Audio Processing\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Configurations\" />
    <Folder Include="Data\" />
    <Folder Include="ExternalServices\Maps\" />
    <Folder Include="ExternalServices\Translation\" />
    <Folder Include="ExternalServices\TextToSpeech\" />
    <Folder Include="ExternalServices\SpeechToText\" />
    <Folder Include="ExternalServices\OpenAI\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

</Project>
